export type BgtiTestAxis = "S" | "L" | "P" | "T";

export const bgtiTestQuestions: ReadonlyArray<{ text: string; axis: BgtiTestAxis; reverse: boolean }> = [
  { text: "나는 내 차례가 오기 전 이미 결정을 마친 상태다.", axis: "S", reverse: false },
  { text: "다른 플레이어의 턴이 3분 이상 길어지면 지루함을 느낀다.", axis: "S", reverse: false },
  { text: "완벽한 한 수보다 흐름을 끊지 않는 빠른 진행이 더 중요하다.", axis: "S", reverse: false },
  { text: "직관적으로 '이거다' 싶은 수를 바로 두는 편이다.", axis: "S", reverse: false },
  { text: "장고(고민)가 길어지는 사람에게 가벼운 눈치를 주는 편이다.", axis: "S", reverse: false },
  { text: "타임 워치(모래시계) 사용에 대해 긍정적이다.", axis: "S", reverse: false },
  { text: "내 차례에 고민을 오래 하면 다른 사람에게 미안한 마음이 든다.", axis: "S", reverse: false },
  { text: "게임 도중 '잠시만요, 다시 할게요'라는 말을 거의 하지 않는다.", axis: "S", reverse: false },
  { text: " '에라 모르겠다' 하고 주사위를 던지는 상황을 즐긴다.", axis: "S", reverse: false },
  { text: "한 판을 길게 하는 것보다 짧게 여러 판 하는 것이 좋다.", axis: "S", reverse: false },
  { text: "모든 경우의 수를 수리적으로 계산한 뒤에야 말을 움직인다.", axis: "S", reverse: true },
  { text: "내 수 하나로 인해 바뀔 3턴 뒤의 상황까지 고려한다.", axis: "S", reverse: true },
  { text: "규칙서의 세부 조항을 확인하느라 게임을 멈추는 일이 잦다.", axis: "S", reverse: true },
  { text: "최선의 수를 찾는 과정 자체가 보드게임의 본질이라 믿는다.", axis: "S", reverse: true },
  { text: "남들이 재촉하면 머릿속이 하얘져서 오히려 더 늦어진다.", axis: "S", reverse: true },
  { text: "점수 계산 단계에서 1점이라도 오차가 생기면 처음부터 다시 계산한다.", axis: "S", reverse: true },
  { text: "브레인 버닝(두뇌 풀가동) 후의 두통을 즐기는 편이다.", axis: "S", reverse: true },
  { text: "다른 사람의 턴에도 그가 어떤 수를 둘지 모든 가능성을 분석한다.", axis: "S", reverse: true },
  { text: " '빨리 좀 하세요'라는 말을 들어본 적이 있다.", axis: "S", reverse: true },
  { text: "복잡한 콤보를 계산하느라 침묵이 흐르는 시간을 견딜 수 있다.", axis: "S", reverse: true },
  { text: "게임 결과가 나오기까지의 시간이 짧을수록 만족도가 높다.", axis: "S", reverse: false },
  { text: "패배하더라도 게임이 빨리 끝났다면 '한 판 더!'를 외치기 쉽다.", axis: "S", reverse: false },
  { text: "나는 '스피드 게임' 종류에 자신이 있다.", axis: "S", reverse: false },
  { text: "수 싸움이 치열한 추상 전략 게임을 할 때 시간 제한이 없길 바란다.", axis: "S", reverse: true },
  { text: "나는 전반적으로 성격이 급하다는 소리를 듣는 편이다.", axis: "S", reverse: false },
  { text: "룰 설명이 15분 이내로 끝나는 게임이 가장 좋다.", axis: "L", reverse: false },
  { text: "컴포넌트가 너무 많아 세팅에 20분 이상 걸리면 지치기 시작한다.", axis: "L", reverse: false },
  { text: "맥주나 간식을 먹으면서 가볍게 웃고 떠들 수 있는 게임이 좋다.", axis: "L", reverse: false },
  { text: "게임 한 판의 총 플레이 시간은 1시간 이내가 적당하다.", axis: "L", reverse: false },
  { text: "복잡한 엔진 빌딩보다는 직관적인 파티 게임이 즐겁다.", axis: "L", reverse: false },
  { text: "새로운 게임을 배울 때 룰북을 미리 읽어오는 숙제는 피하고 싶다.", axis: "L", reverse: false },
  { text: "박스가 작고 휴대하기 편한 게임을 선호한다.", axis: "L", reverse: false },
  { text: "보드게임을 전혀 모르는 사람과도 바로 즐길 수 있는 게임이 좋다.", axis: "L", reverse: false },
  { text: "룰북 페이지 수가 20페이지를 넘어가면 설렌다.", axis: "L", reverse: true },
  { text: "보드게임긱(BGG) 난이도 4.0 이상의 게임에 도전하는 것을 즐긴다.", axis: "L", reverse: true },
  { text: "여러 자원이 유기적으로 순환하는 복잡한 경제 시스템을 좋아한다.", axis: "L", reverse: true },
  { text: "한 판에 3~4시간이 소요되는 대작 게임을 선호한다.", axis: "L", reverse: true },
  { text: "개인판의 공간이 꽉 차고 업그레이드 요소가 많은 것이 좋다.", axis: "L", reverse: true },
  { text: "게임의 잔룰(세부 규칙)이 많을수록 정교한 게임이라고 느낀다.", axis: "L", reverse: true },
  { text: "오토마(1인플 규칙)가 잘 짜인 무거운 게임을 혼자 연구하기도 한다.", axis: "L", reverse: true },
  { text: "게임 플레이보다 세팅과 정리 자체에서도 즐거움을 느낀다.", axis: "L", reverse: true },
  { text: "설명하기 힘든 게임일수록 정복하고 싶은 욕구가 생긴다.", axis: "L", reverse: false },
  { text: "단순한 운 게임보다 실력이 100% 반영되는 게임이 좋다.", axis: "L", reverse: false },
  { text: "긱 순위 상위권의 헤비 유로 게임들을 대부분 소장하고 싶다.", axis: "L", reverse: true },
  { text: "짧은 게임은 '애피타이저'일 뿐, 진정한 게임은 무거워야 한다.", axis: "L", reverse: false },
  { text: "룰 설명을 듣는 시간 자체가 지적인 자극이 되어 즐겁다.", axis: "L", reverse: false },
  { text: "게임 판이 책상 하나를 가득 채울 때 시각적인 쾌감을 느낀다.", axis: "L", reverse: false },
  { text: "방대한 텍스트와 참조표를 수시로 확인해야 하는 게임이 좋다.", axis: "L", reverse: true },
  { text: "한 번의 실수가 게임 전체 패배로 이어지는 엄격한 게임이 좋다.", axis: "L", reverse: true },
  { text: "가벼운 게임은 금방 질린다고 생각한다.", axis: "L", reverse: false },
  { text: "누군가 내 계획(빌드)을 방해하면 게임 의욕이 크게 꺾인다.", axis: "P", reverse: false },
  { text: "협력 게임에서 팀원들과 힘을 합쳐 목표를 달성할 때 가장 행복하다.", axis: "P", reverse: false },
  { text: "남을 공격하기보다 내 개인판을 예쁘게 채우는 것에 더 집중한다.", axis: "P", reverse: false },
  { text: "블러핑(거짓말)을 해야 하는 상황이 오면 마음이 불편하다.", axis: "P", reverse: false },
  { text: " '벽겜'이라는 비판을 들어도 평화로운 게 좋다.", axis: "P", reverse: false },
  { text: "게임 중 누군가 낙오되지 않도록 서로 도와주는 분위기를 선호한다.", axis: "P", reverse: false },
  { text: "남의 자원을 뺏어오는 행동은 웬만하면 하고 싶지 않다.", axis: "P", reverse: false },
  { text: "평화로운 샌드박스형 게임(건설 등)이 취향이다.", axis: "P", reverse: false },
  { text: "상대방의 약점을 파고들어 괴롭히는 것이 보드게임의 묘미다.", axis: "P", reverse: true },
  { text: " '나만 아니면 돼!' 식의 복불복 상황을 즐긴다.", axis: "P", reverse: true },
  { text: "거짓말로 상대를 속이고 승리했을 때 짜릿함을 느낀다.", axis: "P", reverse: true },
  { text: "남이 공들여 만든 것을 파괴하거나 뺏는 카드를 좋아한다.", axis: "P", reverse: true },
  { text: "정치질과 협상을 통해 유리한 고지를 점하는 것에 자신 있다.", axis: "P", reverse: true },
  { text: "1등을 견제하기 위해 다른 플레이어와 일시적인 동맹을 맺는다.", axis: "P", reverse: true },
  { text: "경매 게임에서 상대가 필요한 카드를 비싸게 사게 유도한다.", axis: "P", reverse: true },
  { text: " '헤이트 드래프팅'은 필수 전략이라고 생각한다.", axis: "P", reverse: true },
  { text: "게임 중 말싸움이나 심리전이 오가는 상황이 흥미진진하다.", axis: "P", reverse: false },
  { text: "뒤통수를 치는 배신 요소가 있는 게임을 선호한다.", axis: "P", reverse: true },
  { text: "직접적인 타격이 없는 게임은 밋밋하다고 느낀다.", axis: "P", reverse: false },
  { text: "남의 패를 훔쳐보거나 추리하는 과정이 즐겁다.", axis: "P", reverse: true },
  { text: "평화로운 분위기보다 긴장감 넘치는 대립 구도가 좋다.", axis: "P", reverse: false },
  { text: " '이거 쓰면 기분 나쁘겠지만...'이라며 공격 카드를 내민다.", axis: "P", reverse: true },
  { text: "킹메이킹도 게임의 일부라고 생각한다.", axis: "P", reverse: true },
  { text: "마피아 게임처럼 서로 의심하는 게임에서 에너지를 얻는다.", axis: "P", reverse: true },
  { text: "게임이 끝나고 '왜 나 공격했어?'라고 농담하는 뒤끝이 있다.", axis: "P", reverse: false },
  { text: "카드나 타일의 플레이버 텍스트를 꼭 소리 내어 읽는다.", axis: "T", reverse: false },
  { text: "게임 밸런스가 조금 안 맞더라도 테마가 매력적이면 만족한다.", axis: "T", reverse: false },
  { text: "컴포넌트(피규어 등)의 퀄리티가 몰입에 결정적이다.", axis: "T", reverse: false },
  { text: "나는 내가 특정 캐릭터가 된 것처럼 연기하며 말한다.", axis: "T", reverse: false },
  { text: "룰북 첫 페이지의 배경 이야기는 건너뛰지 않는다.", axis: "T", reverse: false },
  { text: "테마가 없는 추상 전략 게임은 건조하게 느껴진다.", axis: "T", reverse: false },
  { text: "게임 도중 일어나는 불운도 '내 캐릭터의 운명'으로 받아들인다.", axis: "T", reverse: false },
  { text: "아름다운 일러스트가 게임 선택의 80% 이상을 차지한다.", axis: "T", reverse: false },
  { text: "게임의 제목과 박스 아트가 내 취향이어야 손이 간다.", axis: "T", reverse: false },
  { text: "테마는 그저 숫자를 가리기 위한 '껍데기'일 뿐이다.", axis: "T", reverse: true },
  { text: "테마가 아무리 좋아도 규칙이 허술하면 좋은 게임이 아니다.", axis: "T", reverse: true },
  { text: "나는 시스템의 정교함과 수학적 밸런스에 더 감탄한다.", axis: "T", reverse: true },
  { text: "이 게임의 '승리 루트'가 몇 가지인지 분석하는 것이 좋다.", axis: "T", reverse: true },
  { text: "주사위 운보다 실력으로 승부하는 무작위성 없는 게임이 좋다.", axis: "T", reverse: true },
  { text: "규칙의 예외 사항이 적고 깔끔하게 딱 떨어지는 게 좋다.", axis: "T", reverse: true },
  { text: "테마 설명 텍스트보다 아이콘화된 요약이 더 편하다.", axis: "T", reverse: true },
  { text: "게임이 끝난 후 나의 '전략적 실수'를 복기하곤 한다.", axis: "T", reverse: true },
  { text: "어떤 테마를 입혀도 시스템만 재밌으면 상관없다.", axis: "T", reverse: true },
  { text: "점수 계산 방식이 독창적이고 신선한 게임에 높은 점수를 준다.", axis: "T", reverse: true },
  { text: "게임 세계관에 빠지기 위해 관련 영화나 소설을 찾아본다.", axis: "T", reverse: false },
  { text: "몰입도를 위해 배경 음악(BGM)을 트는 것을 선호한다.", axis: "T", reverse: false },
  { text: "게임 엔진이 얼마나 효율적으로 돌아가는지가 최대 관심사다.", axis: "T", reverse: true },
  { text: "특정 행동 시 '테마상 이건 말이 안 되는데?'라고 지적한다.", axis: "T", reverse: false },
  { text: "확률 계산을 통해 기대값이 높은 행동을 선택한다.", axis: "T", reverse: true },
  { text: "게임이 주는 '이야기'보다 '문제 해결의 즐거움'이 더 크다.", axis: "T", reverse: true },
];
